logging.level.org.springframework=DEBUG
logging.level.org.springframework.boot=DEBUG

spring.datasource.url=jdbc:mariadb://localhost:3334/mentoria_spring_security_db
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

jwt.secret=fNu3FAOfNf7fjxKRcbEbDEWw7iFZ4Jl/ewumbaqx3dU=
jwt.expiration=86400000
jwt.access.expiration=86400000
jwt.refresh.expiration=2592000000

spring.email.mailer.gmail.username=ritsure.julai.jose@gmail.com
spring.email.mailer.gmail.password=qgsa kyne zuxd ykem
spring.email.mailer.gmail.host=smtp.gmail.com
spring.email.mailer.gmail.port=587
spring.email.mailer.gmail.tls=true
spring.email.mailer.gmail.auth=true
